algoritmo "semnome"
// Função : Avaliar meus conhecimentos!!!
// Autor : Everton Brasiliano Oliveira da Silva
// Data : 19/06/2017
// Seção de Declarações  To triste com essa prova :(
var
vDia : vetor [1..5,1..2] de inteiro
inicio
// Seção de Comandos
Escreva ("Que dia é hoje?:")
Escreval
Escreval
Leia (vDia [1,1])
escreval
Escreva ("Qual é o dia da semana?:")
Escreval
Escreval
Leia (vDia [1,2])
escreval
Escreva ("Que dia é hoje?:")
Escreval
Escreval
Leia (vDia [2,1])
escreval
Escreva ("Qual é o dia da semana?:")
Escreval
escreval
Leia (vDia [2,2])
escreval
Escreva ("Que dia é hoje?:")
Escreval
escreval
Leia (vDia [3,1])
escreval
Escreva ("Qual é o dia da semana?:")
Escreval
Leia (vDia [3,2])
escreval
Escreva ("Que dia é hoje?:")
Escreval
escreval
Leia (vDia [4,1])
Escreval
Escreva ("Qual é o dia da semana?:")
escreval
Leia (vDia [4,2])
Escreval
escreva("Que dia é hoje?:")
escreval
leia (vDia [5,1])
escreval
escreva ("Qual é o dia da semana?:")
escreval
leia (vDia [5,2])
FIMALGORITMO
