Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/06/2017
Var
// Seção de Declarações das variáveis 

 vQUANTIDADEDIA : inteiro
 vDIA : VETOR [1..5,1..2] DE INTEIRO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 Escreval ("Insira o dia do Mes?")
 PARA vQUANTIDADEDIA DE 1 ATE 5 FACA
 ESCREVA (vQUANTIDADEDIA, " - ")
 LEIA (vDIA[vQUANTIDADEDIA,1])
 FIMPARA

 
 


 
Fimalgoritmo