algoritmo "semnome"
// Função :
// Autor :
// Data : 20/06/2017
// Seção de Declarações
var
Matriz: vetor[1..5,1..2] de inteiro
L,C:inteiro
D, S: inteiro
inicio
// Seção de Comandos
Escreval("Quais dias do mês quer armazenar?")

   para C de 1 ate 2 faca
        para L de 1 ate 5 faca
             leia(matriz[l,c])

        fimpara
        Escreval("Em qual dia da semana cai esse dia?")

   fimpara

fimalgoritmo
