algoritmo "semnome"
// Função :
// Autor :
// Data : 10/11/2015
// Seção de Declarações 
var

dia : inteiro
inicio
// Seção de Comandos
Escreval("Entre com um dia do mês: ")
leia(dia)

Se dia <= 10 entao
     Escreval("Início do mês")
  senao
     se dia <= 20 entao
         Escreval("Meio do mês")
       senao
         se dia <= 31 entao
             Escreval("Fim do mês")
           senao
             Escreval("Dia inválido!")
         fimse
     fimse
fimse


 
fimalgoritmo
