algoritmo "semnome"
// Função :
// Autor :
// Data : 20/06/2017
// Seção de Declarações 
var
matriz : vetor [1..2, 1..5] de inteiro
dia : inteiro

inicio
escreva ("INFORME 5 DIAS DE 1 ATÉ 31:")

  leia (dia)
matriz [1,1] <- dia


se matriz [1,1] = 1  entao
matriz [2,1] <-(1)
senao
se matriz [1,1] = 8  entao
matriz [2,1] <-(1)
senao
se matriz [1,1] = 15  entao
matriz [2,1] <-(1)
senao
se matriz [1,1] = 22  entao
matriz [2,1] <-(1)
senao
se matriz [1,1] = 29  entao
matriz [2,1] <-(1)
senao
se matriz [1,1] = 2 entao
matriz [2,1] <-(2)
senao
se matriz [1,1] = 9 entao
matriz [2,1] <- (2)
senao
se matriz [1,1] = 16 entao
matriz [2,1] <- (2)
senao
se matriz [1,1] = 23 entao
matriz [2,1] <-(2)
senao
se matriz [1,1] = 30 entao
matriz [2,1] <- (2)
senao





se matriz [1,1] = 3 entao
matriz [2,1] <- (3)
senao
se matriz [1,1] = 10 entao
matriz [2,1] <- (3)
senao
se matriz [1,1] = 17 entao
matriz [2,1] <- (3)
senao
se matriz [1,1] = 24 entao
matriz [2,1] <-(3)
senao
se matriz [1,1] = 31 entao
matriz [2,1] <-(3)
senao
se matriz [1,1] = 4 entao
matriz [2,1] <-(4)
senao
se matriz [1,1] = 11 entao
matriz [2,1] <-(4)
senao
se matriz [1,1] = 18 entao
matriz [2,1] <-(4)
senao
se matriz [1,1] = 18 entao
matriz [2,1] <-(4)
senao
se matriz [1,1] = 25 entao
matriz [2,1] <-(4)
senao
se matriz [1,1] = 5 entao
matriz [2,1] <-(5)
senao
se matriz [1,1] = 12 entao
matriz [2,1] <-(5)
senao
se matriz [1,1] = 19 entao
matriz [2,1] <-(5)
senao
se matriz [1,1] = 26 entao
matriz [2,1] <- (5)
senao
se matriz [1,1] = 6 entao
matriz [2,1] <- (6)
senao
se matriz [1,1] = 13 entao
matriz [2,1] <-(6)
senao
se matriz [1,1] = 20 entao
matriz [2,1] <-(6)
senao
se matriz [1,1] = 27 entao
matriz [2,1] <-(6)
senao
se matriz [1,1] = 7 entao
matriz [2,1] <-(7)
senao
se matriz [1,1] = 14 entao
matriz [2,1] <-(7)
senao
se matriz [1,1] = 21 entao
matriz [2,1] <-(7)
senao
se matriz [1,1] = 28 entao
matriz [2,1] <-(7)
senao


fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse


  leia (dia)
matriz [1,2] <- dia


se matriz [1,2] = 1  entao
matriz [2,2] <-(1)
senao
se matriz [1,2] = 8  entao
matriz [2,2] <-(1)
senao
se matriz [1,2] = 15  entao
matriz [2,2] <-(1)
senao
se matriz [1,2] = 22  entao
matriz [2,2] <-(1)
senao
se matriz [1,2] = 29  entao
matriz [2,2] <-(1)
senao
se matriz [1,2] = 2 entao
matriz [2,2] <-(2)
senao
se matriz [1,2] = 9 entao
matriz [2,2] <- (2)
senao
se matriz [1,2] = 16 entao
matriz [2,2] <- (2)
senao
se matriz [1,2] = 23 entao
matriz [2,2] <-(2)
senao
se matriz [1,2] = 30 entao
matriz [2,2] <- (2)
senao
se matriz [1,2] = 3 entao
matriz [2,2] <- (3)
senao
se matriz [1,2] = 10 entao
matriz [2,2] <- (3)
senao
se matriz [1,2] = 17 entao
matriz [2,2] <- (3)
senao
se matriz [1,2] = 24 entao
matriz [2,2] <-(3)
senao
se matriz [1,2] = 31 entao
matriz [2,2] <-(3)
senao
se matriz [1,2] = 4 entao
matriz [2,2] <-(4)
senao
se matriz [1,2] = 11 entao
matriz [2,2] <-(4)
senao
se matriz [1,2] = 18 entao
matriz [2,2] <-(4)
senao
se matriz [1,2] = 18 entao
matriz [2,2] <-(4)
senao
se matriz [1,2] = 25 entao
matriz [2,2] <-(4)
senao
se matriz [1,2] = 5 entao
matriz [2,2] <-(5)
senao
se matriz [1,2] = 12 entao
matriz [2,2] <-(5)
senao
se matriz [1,2] = 19 entao
matriz [2,2] <-(5)
senao
se matriz [1,2] = 26 entao
matriz [2,2] <- (5)
senao
se matriz [1,2] = 6 entao
matriz [2,2] <- (6)
senao
se matriz [1,2] = 13 entao
matriz [2,2] <-(6)
senao
se matriz [1,2] = 20 entao
matriz [2,2] <-(6)
senao
se matriz [1,2] = 27 entao
matriz [2,2] <-(6)
senao
se matriz [1,2] = 7 entao
matriz [2,2] <-(7)
senao
se matriz [1,2] = 14 entao
matriz [2,2] <-(7)
senao
se matriz [1,2] = 21 entao
matriz [2,2] <-(7)
senao
se matriz [1,2] = 28 entao
matriz [2,2] <-(7)
senao


fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse

  leia (dia)
matriz [1,3] <- dia


se matriz [1,3] = 1  entao
matriz [2,3] <-(1)
senao
se matriz [1,3] = 8  entao
matriz [2,3] <-(1)
senao
se matriz [1,3] = 15  entao
matriz [2,3] <-(1)
senao
se matriz [1,3] = 22  entao
matriz [2,3] <-(1)
senao
se matriz [1,3] = 29  entao
matriz [2,3] <-(1)
senao
se matriz [1,3] = 2 entao
matriz [2,3] <-(2)
senao
se matriz [1,3] = 9 entao
matriz [2,3] <- (2)
senao
se matriz [1,3] = 16 entao
matriz [2,3] <- (2)
senao
se matriz [1,3] = 23 entao
matriz [2,3] <-(2)
senao
se matriz [1,3] = 30 entao
matriz [2,3] <- (2)
senao
se matriz [1,3] = 3 entao
matriz [2,3] <- (3)
senao
se matriz [1,3] = 10 entao
matriz [2,3] <- (3)
senao
se matriz [1,3] = 17 entao
matriz [2,3] <- (3)
senao
se matriz [1,3] = 24 entao
matriz [2,3] <-(3)
senao
se matriz [1,3] = 31 entao
matriz [2,3] <-(3)
senao
se matriz [1,3] = 4 entao
matriz [2,3] <-(4)
senao
se matriz [1,3] = 11 entao
matriz [2,3] <-(4)
senao
se matriz [1,3] = 18 entao
matriz [2,3] <-(4)
senao
se matriz [1,3] = 18 entao
matriz [2,3] <-(4)
senao
se matriz [1,3] = 25 entao
matriz [2,3] <-(4)
senao
se matriz [1,3] = 5 entao
matriz [2,3] <-(5)
senao
se matriz [1,3] = 12 entao
matriz [2,3] <-(5)
senao
se matriz [1,3] = 19 entao
matriz [2,3] <-(5)
senao
se matriz [1,3] = 26 entao
matriz [2,3] <- (5)
senao
se matriz [1,3] = 6 entao
matriz [2,3] <- (6)
senao
se matriz [1,3] = 13 entao
matriz [2,3] <-(6)
senao
se matriz [1,3] = 20 entao
matriz [2,3] <-(6)
senao
se matriz [1,3] = 27 entao
matriz [2,3] <-(6)
senao
se matriz [1,3] = 7 entao
matriz [2,3] <-(7)
senao
se matriz [1,3] = 14 entao
matriz [2,3] <-(7)
senao
se matriz [1,3] = 21 entao
matriz [2,3] <-(7)
senao
se matriz [1,3] = 28 entao
matriz [2,3] <-(7)
senao


fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse

  leia (dia)
matriz [1,4] <- dia


se matriz [1,4] = 1  entao
matriz [2,4] <-(1)
senao
se matriz [1,4] = 8  entao
matriz [2,4] <-(1)
senao
se matriz [1,4] = 15  entao
matriz [2,4] <-(1)
senao
se matriz [1,4] = 22  entao
matriz [2,4] <-(1)
senao
se matriz [1,4] = 29  entao
matriz [2,4] <-(1)
senao
se matriz [1,4] = 2 entao
matriz [2,4] <-(2)
senao
se matriz [1,4] = 9 entao
matriz [2,4] <- (2)
senao
se matriz [1,4] = 16 entao
matriz [2,4] <- (2)
senao
se matriz [1,4] = 23 entao
matriz [2,4] <-(2)
senao
se matriz [1,4] = 30 entao
matriz [2,4] <- (2)
senao





se matriz [1,4] = 3 entao
matriz [2,4] <- (3)
senao
se matriz [1,4] = 10 entao
matriz [2,4] <- (3)
senao
se matriz [1,4] = 17 entao
matriz [2,4] <- (3)
senao
se matriz [1,4] = 24 entao
matriz [2,4] <-(3)
senao
se matriz [1,4] = 31 entao
matriz [2,4] <-(3)
senao
se matriz [1,4] = 4 entao
matriz [2,4] <-(4)
senao
se matriz [1,4] = 11 entao
matriz [2,4] <-(4)
senao
se matriz [1,4] = 18 entao
matriz [2,4] <-(4)
senao
se matriz [1,4] = 18 entao
matriz [2,4] <-(4)
senao
se matriz [1,4] = 25 entao
matriz [2,4] <-(4)
senao
se matriz [1,4] = 5 entao
matriz [2,4] <-(5)
senao
se matriz [1,4] = 12 entao
matriz [2,4] <-(5)
senao
se matriz [1,4] = 19 entao
matriz [2,4] <-(5)
senao
se matriz [1,4] = 26 entao
matriz [2,4] <- (5)
senao
se matriz [1,4] = 6 entao
matriz [2,4] <- (6)
senao
se matriz [1,4] = 13 entao
matriz [2,4] <-(6)
senao
se matriz [1,4] = 20 entao
matriz [2,4] <-(6)
senao
se matriz [1,4] = 27 entao
matriz [2,4] <-(6)
senao
se matriz [1,4] = 7 entao
matriz [2,4] <-(7)
senao
se matriz [1,4] = 14 entao
matriz [2,4] <-(7)
senao
se matriz [1,4] = 21 entao
matriz [2,4] <-(7)
senao
se matriz [1,4] = 28 entao
matriz [2,4] <-(7)
senao


fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse


  leia (dia)
matriz [1,5] <- dia


se matriz [1,5] = 1  entao
matriz [2,5] <-(1)
senao
se matriz [1,5] = 8  entao
matriz [2,5] <-(1)
senao
se matriz [1,5] = 15  entao
matriz [2,5] <-(1)
senao
se matriz [1,5] = 22  entao
matriz [2,5] <-(1)
senao
se matriz [1,5] = 29  entao
matriz [2,5] <-(1)
senao
se matriz [1,1] = 2 entao
matriz [2,5] <-(2)
senao
se matriz [1,5] = 9 entao
matriz [2,5] <- (2)
senao
se matriz [1,5] = 16 entao
matriz [2,5] <- (2)
senao
se matriz [1,5] = 23 entao
matriz [2,5] <-(2)
senao
se matriz [1,5] = 30 entao
matriz [2,5] <- (2)
senao





se matriz [1,5] = 3 entao
matriz [2,5] <- (3)
senao
se matriz [1,5] = 10 entao
matriz [2,5] <- (3)
senao
se matriz [1,5] = 17 entao
matriz [2,5] <- (3)
senao
se matriz [1,5] = 24 entao
matriz [2,5] <-(3)
senao
se matriz [1,5] = 31 entao
matriz [2,5] <-(3)
senao
se matriz [1,5] = 4 entao
matriz [2,5] <-(4)
senao
se matriz [1,5] = 11 entao
matriz [2,5] <-(4)
senao
se matriz [1,5] = 18 entao
matriz [2,5] <-(4)
senao
se matriz [1,5] = 18 entao
matriz [2,5] <-(4)
senao
se matriz [1,5] = 25 entao
matriz [2,5] <-(4)
senao
se matriz [1,5] = 5 entao
matriz [2,5] <-(5)
senao
se matriz [1,5] = 12 entao
matriz [2,5] <-(5)
senao
se matriz [1,5] = 19 entao
matriz [2,5] <-(5)
senao
se matriz [1,5] = 26 entao
matriz [2,5] <- (5)
senao
se matriz [1,5] = 6 entao
matriz [2,5] <- (6)
senao
se matriz [1,5] = 13 entao
matriz [2,5] <-(6)
senao
se matriz [1,5] = 20 entao
matriz [2,5] <-(6)
senao
se matriz [1,5] = 27 entao
matriz [2,5] <-(6)
senao
se matriz [1,5] = 7 entao
matriz [2,5] <-(7)
senao
se matriz [1,5] = 14 entao
matriz [2,5] <-(7)
senao
se matriz [1,5] = 21 entao
matriz [2,5] <-(7)
senao
se matriz [1,5] = 28 entao
matriz [2,5] <-(7)
senao


fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimalgoritmo
