algoritmo "semnome"
// Função :
// Autor :
// Data : 19/06/2017
// Seção de Declarações 
var
calendar: vetor [1..5,1..2] de inteiro
dia, semana, contador:  inteiro
inicio
// Seção de Comandos
 
 para  dia de 1 ate 5 faca
          escreva ("Dia do mês:")
          leia (dia)
          calendar[1,1]<- dia
          escreva ("Dia da semana:")
          calendar[2,1]<- semana
          leia (calendar[2,1])
 fimpara
 

 
fimalgoritmo
